### ISSUE TITLE
Open up Zowe Explorer to be used with IntelliJ EAP versions

### ISSUE THREAD

**Issue by recaph** [zowe/zowe-explorer-intellij#109]
Requested to remove the restriction of plugin that prevents installation on all version EAP versions of IntelliJ. 

It may be best to update only minimum version for the plugin as new versions of zowe plugin are released. Many plugins work on this principle already and I don't see a reason why Zowe Explorer can't do the same.

Also, you can feedback about any broken features quickly from people like me who use IntelliJ EAP versions and make this plugin inclusive for other IntelliJ Plugin Developers. or provide Zowe Explorer EAP version.

**Comment by KUGDev** [comment]
Hello @recaph 
Thank you for the issue
We have been investigating this possibility
Sometimes it is impossible to support EAP versions due to platform limitations and breaking changes
Could you please provide any of the plugins that support such feature?

**Comment by recaph** [comment]
Hi @KUGDev many of the plugins out there allow for installation on EAP versions of IntelliJ. 

I completely understand when there are breaking changes with plugins. When I installed IntelliJ EAP, I have done that only after reading below line. My ask is not about that. 

```
Products available under the EAP are pre-release software, which means the stability of EAP builds, 
as well as their applicability for specific purposes, may (and most probably will) vary. 
Please use EAP builds at your own risk.
```

But I would very much want to be able to use the plugin when there is no breaking change in IntelliJ EAP. 

some plugins that allow installation on EAP - sonarlint, scala, etc

**Comment by recaph** [comment]
I believe Jetbrains provides plugin verifier to check compatibility... is it something that could be relied on... during build process...

sonarlint has something like this in its build.gradle
 https://github.com/SonarSource/sonarlint-intellij/blob/d1927335877720f19b5faf41b70e35aea76253b5/build.gradle.kts#L104-L130

**Comment by KUGDev** [comment]
Hi @recaph 
Ok, we will reinvestigate the possibility to provide EAP support
I will update the issue as soon as there is something found

**Comment by KUGDev** [comment]
Hello @recaph 
We've discovered the possibility to provide plugin under EAP version
Starting from 1.0.0 of the plugin, we will be providing EAP version as well as the stable ones

**Comment by recaph** [comment]
@KUGDev thats great to hear is there any ETA for this?

**Comment by KUGDev** [comment]
@recaph we are getting ready
Once the docs are updated on docs.zowe.org, we will be ready to start publishing process

**Comment by recaph** [comment]
Thanks

**Comment by KUGDev** [comment]
Hello @recaph 
We are in process of publishing our plugin
Currently, the v1 is published and is being reviewed
The EAP version is getting ready and will be released a little after

**Comment by recaph** [comment]
@KUGDev looks like a plan…

**Comment by recaph** [comment]
@KUGDev got chance to check this... though I can see the EAP version listed on marketplace, I wasn't able to install it...

![image](https://user-images.githubusercontent.com/704289/227036806-30b28142-3fb3-47c8-a2a4-2593e679f326.png)

Can something be done about this?

**Comment by recaph** [comment]
@KUGDev IntelliJ build is Build #IU-231.8109.90, built on March 16, 2023
![image](https://user-images.githubusercontent.com/704289/227248298-4049831f-ef4e-42bb-af17-ea2b9ba0d191.png)

I was able to download and install via zip option though... but it didn't get listed in marketplace...
![image](https://user-images.githubusercontent.com/704289/227248951-4b00dbeb-b822-4dd3-ae95-dcfb5fbecab2.png)
![image](https://user-images.githubusercontent.com/704289/227249022-d09e037d-46c0-4de6-86f9-3c6edf154560.png)

**Comment by KUGDev** [comment]
Hello @recaph 
It looks like the EAP version of the IntelliJ works differently from the stable version, so it is impossible to provide the plugin inside the IntelliJ's marketplace directly in IDE.
So the only way to install the plugin is through the .zip from a web version of the marketplace.
I've tried some ways to make it work, but looks like there is no other way for now, sorry.

**Comment by recaph** [comment]
@KUGDev I confirm that I was able to install Zowe Explorer directly from marketplace yesterday... Thank you very much... 

This is my last comment on this issue... I will create new ones if I see any further issues during my usage...

![image](https://user-images.githubusercontent.com/704289/233116663-a893ec3c-805c-4718-9ba2-bd0aad8339ca.png)

**Comment by KUGDev** [comment]
@recaph cool! Will be glad to help with issues, if any:)
