### ISSUE TITLE
Memory consumption of the plugin

### ISSUE THREAD

**Issue by pinpan** [zowe/zowe-explorer-intellij#11]
The IDEA started for testing the plugin, went very quickly to Low Memory state.

**Comment by KUGDev** [comment]
Hello @pinpan 
We went through the investigation on memory usage
Looks like it is an IntelliJ problem. It appears to be during the indexing process. The plugin has almost no impact on it. But it looks like the low memory state does not prevent the user from interacting with IntelliJ and the plugin. If you encounter some issues/lagging, try the following:
https://www.jetbrains.com/help/idea/increasing-memory-heap.html
If you have some other issues according to this problem, we are open to discussing, investigating, and fixing
