### ISSUE TITLE
CLEARTEXT communication not enabled for client

### ISSUE THREAD

**Issue by michiiee93** [zowe/zowe-explorer-intellij#136]
Our z/OSMF is currently not supporting HTTPS, therefore I cannot connect to it by https://URL.
When i try to connect by HTTP://URL to our z/OS, i am getting:
"CLEARTEXT communication not enabled for client".
Any idea how i can allow this in phpstorm?
In VS Code I am able to connect with the ZOWE extension by HTTP.

**Comment by KUGDev** [comment]
Hello @michiiee93 
We do not support HTTP, but probably, it would be better to add such option
We will investigate and implement this asap

**Comment by michiiee93** [comment]
Hi! Thanks for the very quick response! That would be great, otherwise, I would just switch to VSCode until we have HTTPS on our z/OS running.
