### ISSUE TITLE
Error creating dataset

### ISSUE THREAD

**Issue by pinpan** [zowe/zowe-explorer-intellij#15]
Received 404 when trying to create new dataset.
The values submitted were the default ones, so most probably not sufficient and not correct at all, but HTTP 404 was not expected as a valid response.

![image](https://user-images.githubusercontent.com/3938398/159483446-434a66d4-f398-4663-8b37-3d74cee11df7.png)

**Comment by KUGDev** [comment]
Must have been fixed in 0.2 version
