### ISSUE TITLE
Support for newer versions of IntelliJ including EAP versions

### ISSUE THREAD

**Issue by recaph** [zowe/zowe-explorer-intellij#17]
Unable to use the Zowe Explorer plugin 

![image](https://user-images.githubusercontent.com/704289/163004628-b1465209-63e7-4b34-ae45-5fb6ca717afa.png)
![image](https://user-images.githubusercontent.com/704289/163004703-96fbfd0e-2701-42b6-be99-0162145ede7f.png)

**Comment by KUGDev** [comment]
Hi @recaph 
Thank you for the issue
It will be resolved ASAP

**Comment by recaph** [comment]
Thank you very much team//. I was able to install and use the plugin on IntelliJ IDEA 2022.1.1 RC successfully...

**Comment by KUGDev** [comment]
Hi @recaph 
Thank you for your feedback!
We hope you enjoy using the plugin
