### ISSUE TITLE
Copy uss-file with the same name to PDS does not change file's content in PDS in plugin

### ISSUE THREAD

**Issue by KUGDev** [zowe/zowe-explorer-intellij#19]
Steps:
1. copy uss-file to PDS;
2. do changes in the file from step1 on uss;
3. copy again this changed uss-file to the same PDS with "Overwrite for All" option => content of the file is not changed in the PDS even after Refresh. 
P.S. on zOs side the file's content is changed

**Comment by ATsikhamirau** [comment]
This bug is not reproducible anymore.
