### ISSUE TITLE
JES Explorer tab has delete option disabled and missing edit option  

### ISSUE THREAD

**Issue by shabaz213** [zowe/zowe-explorer-intellij#5]
In the JES Explorer tab, I see the **Delete** option is disabled to delete any filters or working sets. Also, the **Edit** option is also missing.

![image](https://user-images.githubusercontent.com/45122159/156495958-cbc19a8d-c0a7-4d44-b4df-d182d9f72b0e.png)

**Comment by KUGDev** [comment]
Hi @shabaz213 
Thanks for the issue created
Currently, it is working as designed, but some mainframe-specific features are not ready yet, so we are planning to add this functional in next releases
