### ISSUE TITLE
'Zowe Explorer 0.2.1' installation does remove 'For Mainframe 0.6.1' from IntellJ 2021.3.2 and vice versa

### ISSUE THREAD

**Issue by VAranouski** [zowe/zowe-explorer-intellij#77]
Hi,
I have upgraded 'For Mainframe' plugin to v 0.6.1. Then I installed 'Zowe Explorer' v0.2.1.
I expected to see both plugins available in my IntellJ 2021.3.2 Community Edition.
But it seems 'Zowe Explorer' replaced 'For Mainframe'.
I tried to install 'For Mainframe' plugin once again.
This time 'Zowe Explorer' disappeared from the list of installed plugins.
The restart of IDE did not help.

**Comment by KUGDev** [comment]
Problem is not reproducible anymore (v0.3.0)
