### ISSUE TITLE
Separate Working Set and Jobs Working set tabs

### ISSUE THREAD

**Issue by pinpan** [zowe/zowe-explorer-intellij#9]
Are separate Working Set and Jobs Working set tabs are needed?

**Comment by KUGDev** [comment]
Hello @pinpan 
Jobs Working Set and Working Set tabs are separated as we don't want to mix up jobs and files/datasets between each other. They have separate functionality and definition

**Comment by pinpan** [comment]
Agree with that. Can be closed. Thank you!
